group_names: ['msm_white_male', 'msm_black_male', 'msm_hisp_male', 'idu_white_male', 'idu_black_male',
              'idu_hisp_male', 'idu_white_female', 'idu_black_female', 'idu_hisp_female', 'het_white_male',
              'het_black_male', 'het_hisp_male', 'het_white_female', 'het_black_female', 'het_hisp_female']
num_cpus: 50
replications: 200
comorbidity_flag: 0
new_dx: 'base'
record_tv_cd4: False
verbose: False
sa_dict: {'lambda1':               null,
          'mu1':                   null,
          'mu2':                   null,
          'sigma1':                null,
          'sigma2':                null,
          'mortality_in_care':     null,
          'mortality_out_care':    null,
          'loss_to_follow_up':     null,
          'cd4_increase':          null,
          'cd4_decrease':          null,
          'new_pop_size':          null}
