group_names: ['msm_white_male', 'msm_black_male', 'msm_hisp_male', 'idu_white_male', 'idu_black_male',
              'idu_hisp_male', 'idu_white_female', 'idu_black_female', 'idu_hisp_female', 'het_white_male',
              'het_black_male', 'het_hisp_male', 'het_white_female', 'het_black_female', 'het_hisp_female']
num_cpus: 50
replications: 200
comorbidity_flag: 0
mm_detail_flag: 0
new_dx: 'ehe'
morality_model: 'base'
mortality_threshold_flag: 1
final_year: 2030
verbose: 0
