group_names: ['msm_white_male', 'msm_black_male', 'msm_hisp_male']
num_cpus: 50
replications: 200
comorbidity_flag: 0
mm_detail_flag: 0
new_dx: 'base'
mortality_model: 'base'
mortality_threshold: 1
final_year: 2031
verbose: 0
