group_names: ['idu_black_female']
num_cpus: 1
replications: 1
comorbidity_flag: 1
new_dx: 'base'
mortality_model: 'by_sex_race_risk'
mortality_threshold_flag: 1
final_year: 2030
verbose: 1
sa_type: 'none'
idu_threshold: '2x'
bmi_intervention: 0
bmi_intervention_probability: 1.0
