group_names: ['het_white_female', 'idu_black_male']
num_cpus: 4
replications: 2
comorbidity_flag: 0
new_dx: 'base'
mortality_model: 'base' # base, by_sex, by_sex_race
mortality_threshold_flag: 1 # 1, 0
final_year: 2030
verbose: 0
sa_type: 'none'
