name: python

on: [pull_request]

jobs:
  build_and_test:
   runs-on: ubuntu-latest
  
   steps:
     - uses: actions/checkout@v4
     - name: Build Docker image 
       run: docker build -t pearl_model .
     - name: Run tests inside the container
       run: docker run pearl_model pytest tests/
     - name: mypy
       run: docker run pearl_model mypy src/
     - name: ruff
       run: docker run pearl_model ruff check src/ tests/
