name: python

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image 
        run: docker build . -t ghcr.io/${{ github.repository_owner }}/pearl_model:latest

      - name: Run tests inside the container
        run: docker run ghcr.io/${{ github.repository_owner }}/pearl_model:latest pytest tests/

      - name: mypy
        run: docker run ghcr.io/${{ github.repository_owner }}/pearl_model:latest mypy src/

      - name: ruff
        run: docker run ghcr.io/${{ github.repository_owner }}/pearl_model:latest ruff check src/ tests/
     
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/pearl_model:latest
       
