name: python

on: [push, pull_request]

env:
  PYTHON_VERSION: "3.11"

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [ "3.11"]
    steps:
      - name: Install Nox
        run: pip install --only nox
      - name: Test with Nox
        run: nox -s test-${{ matrix.python-version }}
